github:
	ghp-import -p renderer
EXAMPLES_FILE=renderer/examples.js
GITHUB_PAGES_FOLDER=renderer
GITHUB_PAGES_BRANCH=gh-pages

deploy:
	echo "// This file is autogenerated, do not modify it directly." > $(EXAMPLES_FILE); \
	echo "var examples = {}" >> $(EXAMPLES_FILE); \
	for f in data/*.json; do \
		c=`go run git2graph.go -f $$f`; \
		echo "examples['$$f'] = '$$c';" >> $(EXAMPLES_FILE); \
	done
.PHONY: deploy github
